version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - task-api-network

  task-api:
    build: .
    container_name: task-api
    ports:
      - "5000:5000"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKey
      - AWS_SECRET_ACCESS_KEY=fakeSecretKey
    depends_on:
      - dynamodb-local
    networks:
      - task-api-network

networks:
  task-api-network:
    driver: bridge